import type { OptionSelect } from "~/entities/common";

/**
 * SCHOOL TYPE
 */
export const SCHOOL_TYPE_ENUM = {
  PRE_SCHOOL: 0,
  PRIMARY_SCHOOL: 1,
  MIDDLE_SCHOOL: 2,
  HIGH_SCHOOL: 3,
};

export const SCHOOL_TYPE = {
  [SCHOOL_TYPE_ENUM.PRE_SCHOOL]: "Mầm non",
  [SCHOOL_TYPE_ENUM.PRIMARY_SCHOOL]: "Tiểu học",
  [SCHOOL_TYPE_ENUM.MIDDLE_SCHOOL]: "Trung học cơ sở",
  [SCHOOL_TYPE_ENUM.HIGH_SCHOOL]: "Trung học phổ thông",
};

export const SCHOOL_TYPE_OPTIONS: OptionSelect[] = [
  {
    id: SCHOOL_TYPE_ENUM.PRE_SCHOOL,
    name: SCHOOL_TYPE[SCHOOL_TYPE_ENUM.PRE_SCHOOL],
  },
  {
    id: SCHOOL_TYPE_ENUM.PRIMARY_SCHOOL,
    name: SCHOOL_TYPE[SCHOOL_TYPE_ENUM.PRIMARY_SCHOOL],
  },
  {
    id: SCHOOL_TYPE_ENUM.MIDDLE_SCHOOL,
    name: SCHOOL_TYPE[SCHOOL_TYPE_ENUM.MIDDLE_SCHOOL],
  },
  {
    id: SCHOOL_TYPE_ENUM.HIGH_SCHOOL,
    name: SCHOOL_TYPE[SCHOOL_TYPE_ENUM.HIGH_SCHOOL],
  },
];

/**
 * For schedule
 */
export const SCHEDULE_TYPE_ENUM = {
  CLASS: 0,
  GRADE: 1,
  SCHOOL: 2,
};

export const SCHEDULE_TYPE_NAME = {
  [SCHEDULE_TYPE_ENUM.CLASS]: "Theo lớp",
  [SCHEDULE_TYPE_ENUM.GRADE]: "Theo khối",
  [SCHEDULE_TYPE_ENUM.SCHOOL]: "Toàn trường",
};

export const SCHEDULE_TYPE_OPTIONS: OptionSelect[] = [
  {
    id: SCHEDULE_TYPE_ENUM.CLASS,
    name: SCHEDULE_TYPE_NAME[SCHEDULE_TYPE_ENUM.CLASS],
  },
  {
    id: SCHEDULE_TYPE_ENUM.GRADE,
    name: SCHEDULE_TYPE_NAME[SCHEDULE_TYPE_ENUM.GRADE],
  },
  {
    id: SCHEDULE_TYPE_ENUM.SCHOOL,
    name: SCHEDULE_TYPE_NAME[SCHEDULE_TYPE_ENUM.SCHOOL],
  },
];

/**
 * For Session
 */
export const SCHEDULE_SESSION_ENUM = {
  MORNING: 0,
  AFTERNOON: 1,
  FULL_DAY: 2,
};

export const SCHEDULE_SESSION_NAME = {
  [SCHEDULE_SESSION_ENUM.MORNING]: "Sáng",
  [SCHEDULE_SESSION_ENUM.AFTERNOON]: "Chiều",
  [SCHEDULE_SESSION_ENUM.FULL_DAY]: "Cả ngày",
};

export const SCHEDULE_SESSION_OPTIONS: OptionSelect[] = [
  {
    id: SCHEDULE_SESSION_ENUM.MORNING,
    name: SCHEDULE_SESSION_NAME[SCHEDULE_SESSION_ENUM.MORNING],
  },
  {
    id: SCHEDULE_SESSION_ENUM.AFTERNOON,
    name: SCHEDULE_SESSION_NAME[SCHEDULE_SESSION_ENUM.AFTERNOON],
  },
  {
    id: SCHEDULE_SESSION_ENUM.FULL_DAY,
    name: SCHEDULE_SESSION_NAME[SCHEDULE_SESSION_ENUM.FULL_DAY],
  },
];

export const SCHEDULE_SESSION_COLOR_ENUM = {
  [SCHEDULE_SESSION_ENUM.MORNING]: "indigo",
  [SCHEDULE_SESSION_ENUM.AFTERNOON]: "orange",
  [SCHEDULE_SESSION_ENUM.FULL_DAY]: "green",
};
